#ifndef _CURRENCYTYPE_H_
#define _CURRENCYTYPE_H_

enum class CURRENCY_TYPE {
    CURRENCY_MONEY = 0,
    CURRENCY_BIND_MONEY = 1,
    CURRENCY_GOLD = 2,
    CURRENCY_BIND_GOLD = 3,
    CURRENCY_HONOR = 4,
    CURRENCY_VIGOUR = 5,
    CURRENCY_CONTRIBUTION = 6,
    CURRENCY_AC_SOCRE = 7,
    CURRENCY_BOSS_SCORE = 8,
    CURRENCY_CASH = 9,
    CURRENCY_MAX = 12
};

// CURRENCY_CHANGE_REASON is defined in Common/CommonTypes.h

#endif // _CURRENCYTYPE_H_
